#!/usr/bin/env bash
set -Eeuo pipefail
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")"&&pwd -P);source "$SCRIPT_DIR/lib-common.sh";require_executed
require_cmd jq;require_cmd git;require_cmd gh;root=$(repo_root);cd "$root";repo=$(origin_repo);default=$(default_branch);branch=$(git branch --show-current);p=$(collab_profile_json pr);pr=${1:-$(jq -r '.prNumber//empty'<<<"$p")};(($#<=1))||usage_error 'Usage: collab-pr-finalize.sh [NUMBER]'
if [[ -z $pr ]];then m=$(gh pr list --repo "$repo" --head "$branch" --state open --json number);[[ $(jq length<<<"$m")==1 ]]||die "expected one open PR for $branch";pr=$(jq -r '.[0].number'<<<"$m");fi
[[ $pr =~ ^[0-9]+$ ]]||usage_error 'PR must be numeric';clean_tree||die 'working tree must be clean';data=$(gh pr view "$pr" --repo "$repo" --json state,isDraft,baseRefName,headRefName,headRefOid,mergeable,statusCheckRollup,url)
[[ $(jq -r .state<<<"$data")==OPEN ]]||die 'PR is not open';[[ $(jq -r .isDraft<<<"$data")==false ]]||die 'PR is a draft';[[ $(jq -r .baseRefName<<<"$data")=="$default" ]]||die 'wrong base';[[ $(jq -r .headRefName<<<"$data")=="$branch" ]]||die 'wrong head branch';[[ $(jq -r .mergeable<<<"$data")!=CONFLICTING ]]||die 'PR has conflicts'
remembered_repo=$(jq -r '.repository//empty'<<<"$p");remembered_branch=$(jq -r '.branch//empty'<<<"$p");remembered_head=$(jq -r '.head//empty'<<<"$p");[[ -z $remembered_repo||$remembered_repo == "$repo" ]]||die 'remembered PR belongs to another repository';[[ -z $remembered_branch||$remembered_branch == "$branch" ]]||die 'remembered PR belongs to another branch';[[ -z $remembered_head||$remembered_head == "$(jq -r .headRefOid<<<"$data")" ]]||die 'remembered PR is stale'
"$SCRIPT_DIR/collab-work-verify.sh";failed=$(jq '[.statusCheckRollup[]?|select((.conclusion//"")|test("FAILURE|CANCELLED|TIMED_OUT|ACTION_REQUIRED"))]|length'<<<"$data");pending=$(jq '[.statusCheckRollup[]?|select((.status//.state//"")|test("PENDING|QUEUED|IN_PROGRESS|EXPECTED"))]|length'<<<"$data");((failed==0&&pending==0))||die 'checks are failed or pending'
gh pr merge "$pr" --repo "$repo" --squash --delete-branch;git switch "$default";git pull --ff-only origin "$default";"$SCRIPT_DIR/collab-repo-verify.sh";gh pr view "$pr" --repo "$repo" --json state,mergedAt,mergeCommit,url
