#!/usr/bin/env bash
set -Eeuo pipefail
D=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P); source "$D/lib-common.sh"; require_executed
ROLE=''; REPO=''; OUT=''; MAX=262144; RECENT=20; GH=1; IN=(); EX=(); CROOT=''; CIN=(); ISSUE=''; ALL=0; FILES=1; BRIEF=''; OUTX=0
collab_profile_load context; PROFILE_ROLE=$ROLE; PROFILE_OUT=$OUT
while (($#)); do case "$1" in --role) ROLE=$2;shift 2;;--repo)REPO=$2;shift 2;;--out)OUT=$2;OUTX=1;shift 2;;--include)IN+=("$2");shift 2;;--exclude)EX+=("$2");shift 2;;--max-file-bytes)MAX=$2;shift 2;;--recent-commits)RECENT=$2;shift 2;;--recent-closed)RECENT_CLOSED=$2;shift 2;;--no-github)GH=0;shift;;--no-files)FILES=0;shift;;--issue)ISSUE=$2;shift 2;;--all-open-issue-bodies)ALL=1;shift;;--delivery-brief)BRIEF=$2;shift 2;;--consumer-root)CROOT=$2;shift 2;;--consumer-include)CIN+=("$2");shift 2;;-h|--help)echo 'Usage: collab-context-collect.sh --role lead|senior [options]';exit 0;;--version)echo 'collab-context-collect.sh 1.2.0';exit 0;;*)usage_error "unknown argument: $1";;esac;done
[[ $ROLE == lead || $ROLE == senior ]] || usage_error '--role is required and must be lead or senior'
if ((OUTX==0)); then [[ $ROLE == "$PROFILE_ROLE" && -n $PROFILE_OUT ]] && OUT=$PROFILE_OUT || OUT=".dx/${ROLE}-context.md"; fi
args=(render-context --root . --out "$OUT" --max-bytes "$MAX" --recent-commits "$RECENT"); [[ -n $REPO ]]&&args+=(--repo "$REPO"); ((GH))||args+=(--no-github); ((FILES))||IN=(); for x in "${IN[@]}";do args+=(--include "$x");done;for x in "${EX[@]}";do args+=(--exclude "$x");done; [[ -z $CROOT ]]||args+=(--consumer-root "$CROOT");for x in "${CIN[@]}";do args+=(--consumer-include "$x");done
python3 "$D/collab-evidence.py" "${args[@]}"
MAX_FILE_BYTES=$MAX;RECENT_COMMITS=$RECENT;RECENT_CLOSED=${RECENT_CLOSED:-20};WITH_GITHUB=$GH;WITH_FILES=$FILES;ALL_OPEN_ISSUE_BODIES=$ALL;DELIVERY_BRIEF=$BRIEF;CONSUMER_ROOT=$CROOT;EXPECTED_REPO=$REPO;INCLUDES=("${IN[@]}");EXCLUDES=("${EX[@]}");CONSUMER_INCLUDES=("${CIN[@]}");collab_profile_save context ROLE ISSUE EXPECTED_REPO OUT MAX_FILE_BYTES RECENT_COMMITS RECENT_CLOSED WITH_GITHUB WITH_FILES ALL_OPEN_ISSUE_BODIES DELIVERY_BRIEF CONSUMER_ROOT INCLUDES EXCLUDES CONSUMER_INCLUDES
collab_record_run context success "$OUT" >/dev/null; echo "Context written: $(python3 -c 'from pathlib import Path;import sys;print(Path(sys.argv[1]).resolve())' "$OUT")"